name: Pull Request Closed into Develop Branch Continuous Integration
on:
  pull_request:
    types: [closed]
    branches: [develop]

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Opening pull request
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: develop
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
